# Generated by Django 4.1.2 on 2022-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='no_of_vacancy',
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(),
        ),
    ]
