# Generated by Django 4.1.2 on 2022-10-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('no_of_vacancy', models.IntegerField()),
            ],
        ),
    ]
