# Generated by Django 4.1.2 on 2022-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdescrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('no_of_vacancy', models.IntegerField()),
                ('experience', models.TextField()),
                ('documents', models.TextField()),
                ('skill', models.TextField()),
                ('language', models.TextField()),
                ('salary', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='jobs',
        ),
    ]
