# Generated by Django 4.1.2 on 2022-10-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_jobdescrip_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='Category_id',
        ),
        migrations.AlterField(
            model_name='jobdescrip',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdescrip', to='web.categories'),
        ),
    ]
