# Generated by Django 4.1.2 on 2022-10-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_jobdescrip_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescrip',
            old_name='Category',
            new_name='Categorys',
        ),
    ]
