# Generated by Django 4.1.2 on 2022-10-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_category_jobdescrip_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescrip',
            name='Categorys',
        ),
    ]
