# Generated by Django 4.1.2 on 2022-10-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_jobdescrip_description_jobdescrip_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescrip',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categories'),
        ),
    ]
