# Generated by Django 4.1.2 on 2022-10-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_jobdescrip_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobdescrip',
        ),
    ]
