# Generated by Django 4.1.2 on 2022-10-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_jobdescrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdescrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('no_of_vacancy', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('experience', models.TextField()),
                ('documents', models.TextField()),
                ('skill', models.TextField()),
                ('language', models.TextField()),
                ('salary', models.TextField()),
                ('age', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categories')),
            ],
        ),
    ]
